"""Add Click model

Revision ID: ae552a3bb798
Revises: c0df6b1f954e
Create Date: 2020-03-22 21:53:11.265902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae552a3bb798'
down_revision = 'c0df6b1f954e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorturls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clicks',
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('number_of_clicks', sa.Integer(), nullable=True),
    sa.Column('short_url_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['short_url_id'], ['shorturls.id'], ),
    sa.PrimaryKeyConstraint('short_url')
    )
    op.drop_table('short_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('long_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('short_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='short_url_pkey')
    )
    op.drop_table('clicks')
    op.drop_table('shorturls')
    # ### end Alembic commands ###
